---
- name: MySQL本体のインストール
  apt: name={{ item }} state=latest
  with_items:
    - python-mysqldb
    - mysql-server-5.6 
  tags: mysql


- name: rootのパスワード変更
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: 不要なユーザの削除
  mysql_user: user="" host={{ ansible_hostname }} state="absent" login_user=root login_password={{ mysql_root_password }} login_host=localhost
  tags: mysql

- name: 不要なユーザの削除
  mysql_user: user="" state="absent" login_user=root login_password={{ mysql_root_password }} login_host=localhost
  tags: mysql

- name: 不要なユーザの削除
  mysql_user: user="debian-sys-maint" state="absent" login_user=root login_password={{ mysql_root_password }} login_host=localhost
  tags: mysql

- name: 不要なテーブルの削除
  action: mysql_db db=test state=absent login_user=root login_password={{ mysql_root_password }} login_host=localhost
  tags: mysql

- name: MySQLの設定ファイルを作成
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root mode=0600
  notify:
    - restart mysql
  tags: mysql

- name: MySQL開始
  service: name=mysql state=started enabled=yes
  tags: mysql
